homePage=https://tutorialsninja.com/demo/index.php?route=common/home
registerPage=https://tutorialsninja.com/demo/index.php?route=account/register
acountCreatedPage=https://tutorialsninja.com/demo/index.php?route=account/success
loginPage=https://tutorialsninja.com/demo/index.php?route=account/login
forgotPasswordPage=https://tutorialsninja.com/demo/index.php?route=account/forgotten
acountPage=https://tutorialsninja.com/demo/index.php?route=account/account
productComparisonPage=https://tutorialsninja.com/demo/index.php?route=product/compare
wishlistPage=https://tutorialsninja.com/demo/index.php?route=account/wishlist
shoppingCartPage=https://tutorialsninja.com/demo/index.php?route=checkout/cart
contactUsPage=https://tutorialsninja.com/demo/index.php?route=information/contact
contactUsSuccess=https://tutorialsninja.com/demo/index.php?route=information/contact/success

invalidNameFieldMessage="Name must be between 3 and 32 characters!"
invalidEmailFieldMessage="E-Mail Address does not appear to be valid!"
invalidEnquiryFieldMessage="Enquiry must be between 10 and 3000 characters!"
macbookAdded= 1 item(s) - $602.00
iphoneAdded= 1 item(s) - $123.20




